// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dutyarea.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "dutyarea.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* DutyAreaRequest_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DutyAreaRequest_reflection_ = NULL;
const ::google::protobuf::Descriptor* DutyAreaRepsone_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  DutyAreaRepsone_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_dutyarea_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_dutyarea_2eproto() {
  protobuf_AddDesc_dutyarea_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "dutyarea.proto");
  GOOGLE_CHECK(file != NULL);
  DutyAreaRequest_descriptor_ = file->message_type(0);
  static const int DutyAreaRequest_offsets_[12] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, name_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, point_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, linestyle_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, fullstyle_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, linewidth_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, dutyman_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, drawman_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, isshare_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, linecolor_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, fullcolor_),
  };
  DutyAreaRequest_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      DutyAreaRequest_descriptor_,
      DutyAreaRequest::internal_default_instance(),
      DutyAreaRequest_offsets_,
      -1,
      -1,
      -1,
      sizeof(DutyAreaRequest),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRequest, _internal_metadata_));
  DutyAreaRepsone_descriptor_ = file->message_type(1);
  static const int DutyAreaRepsone_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRepsone, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRepsone, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRepsone, dutyareas_),
  };
  DutyAreaRepsone_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      DutyAreaRepsone_descriptor_,
      DutyAreaRepsone::internal_default_instance(),
      DutyAreaRepsone_offsets_,
      -1,
      -1,
      -1,
      sizeof(DutyAreaRepsone),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(DutyAreaRepsone, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_dutyarea_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      DutyAreaRequest_descriptor_, DutyAreaRequest::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      DutyAreaRepsone_descriptor_, DutyAreaRepsone::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_dutyarea_2eproto() {
  DutyAreaRequest_default_instance_.Shutdown();
  delete DutyAreaRequest_reflection_;
  DutyAreaRepsone_default_instance_.Shutdown();
  delete DutyAreaRepsone_reflection_;
}

void protobuf_InitDefaults_dutyarea_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_InitDefaults_PointMes_2eproto();
  ::google::protobuf::internal::GetEmptyString();
  DutyAreaRequest_default_instance_.DefaultConstruct();
  ::google::protobuf::internal::GetEmptyString();
  DutyAreaRepsone_default_instance_.DefaultConstruct();
  DutyAreaRequest_default_instance_.get_mutable()->InitAsDefaultInstance();
  DutyAreaRepsone_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_dutyarea_2eproto_once_);
void protobuf_InitDefaults_dutyarea_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_dutyarea_2eproto_once_,
                 &protobuf_InitDefaults_dutyarea_2eproto_impl);
}
void protobuf_AddDesc_dutyarea_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_dutyarea_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\016dutyarea.proto\032\016PointMes.proto\"\345\001\n\017Dut"
    "yAreaRequest\022\014\n\004type\030\001 \001(\005\022\n\n\002ID\030\002 \001(\t\022\014"
    "\n\004name\030\003 \001(\t\022\030\n\005point\030\004 \003(\0132\t.PointMes\022\021"
    "\n\tlinestyle\030\005 \001(\005\022\021\n\tfullstyle\030\006 \001(\005\022\021\n\t"
    "linewidth\030\007 \001(\005\022\017\n\007dutyman\030\010 \001(\t\022\017\n\007draw"
    "man\030\t \001(\t\022\017\n\007isshare\030\n \001(\010\022\021\n\tlinecolor\030"
    "\013 \001(\t\022\021\n\tfullcolor\030\014 \001(\t\"T\n\017DutyAreaReps"
    "one\022\014\n\004type\030\001 \001(\005\022\016\n\006result\030\002 \001(\t\022#\n\tdut"
    "yareas\030\003 \003(\0132\020.DutyAreaRequestb\006proto3", 358);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "dutyarea.proto", &protobuf_RegisterTypes);
  ::protobuf_AddDesc_PointMes_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_dutyarea_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_dutyarea_2eproto_once_);
void protobuf_AddDesc_dutyarea_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_dutyarea_2eproto_once_,
                 &protobuf_AddDesc_dutyarea_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_dutyarea_2eproto {
  StaticDescriptorInitializer_dutyarea_2eproto() {
    protobuf_AddDesc_dutyarea_2eproto();
  }
} static_descriptor_initializer_dutyarea_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DutyAreaRequest::kTypeFieldNumber;
const int DutyAreaRequest::kIDFieldNumber;
const int DutyAreaRequest::kNameFieldNumber;
const int DutyAreaRequest::kPointFieldNumber;
const int DutyAreaRequest::kLinestyleFieldNumber;
const int DutyAreaRequest::kFullstyleFieldNumber;
const int DutyAreaRequest::kLinewidthFieldNumber;
const int DutyAreaRequest::kDutymanFieldNumber;
const int DutyAreaRequest::kDrawmanFieldNumber;
const int DutyAreaRequest::kIsshareFieldNumber;
const int DutyAreaRequest::kLinecolorFieldNumber;
const int DutyAreaRequest::kFullcolorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DutyAreaRequest::DutyAreaRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_dutyarea_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:DutyAreaRequest)
}

void DutyAreaRequest::InitAsDefaultInstance() {
}

DutyAreaRequest::DutyAreaRequest(const DutyAreaRequest& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DutyAreaRequest)
}

void DutyAreaRequest::SharedCtor() {
  id_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dutyman_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  drawman_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  linecolor_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fullcolor_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&type_, 0, reinterpret_cast<char*>(&isshare_) -
    reinterpret_cast<char*>(&type_) + sizeof(isshare_));
  _cached_size_ = 0;
}

DutyAreaRequest::~DutyAreaRequest() {
  // @@protoc_insertion_point(destructor:DutyAreaRequest)
  SharedDtor();
}

void DutyAreaRequest::SharedDtor() {
  id_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dutyman_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  drawman_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  linecolor_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fullcolor_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DutyAreaRequest::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DutyAreaRequest::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DutyAreaRequest_descriptor_;
}

const DutyAreaRequest& DutyAreaRequest::default_instance() {
  protobuf_InitDefaults_dutyarea_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<DutyAreaRequest> DutyAreaRequest_default_instance_;

DutyAreaRequest* DutyAreaRequest::New(::google::protobuf::Arena* arena) const {
  DutyAreaRequest* n = new DutyAreaRequest;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DutyAreaRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:DutyAreaRequest)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(DutyAreaRequest, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<DutyAreaRequest*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&(first), 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(type_, linewidth_);
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dutyman_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  drawman_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  isshare_ = false;
  linecolor_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  fullcolor_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());

#undef ZR_HELPER_
#undef ZR_

  point_.Clear();
}

bool DutyAreaRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DutyAreaRequest)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 type = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_ID;
        break;
      }

      // optional string ID = 2;
      case 2: {
        if (tag == 18) {
         parse_ID:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_id()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->id().data(), this->id().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DutyAreaRequest.ID"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_name;
        break;
      }

      // optional string name = 3;
      case 3: {
        if (tag == 26) {
         parse_name:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), this->name().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DutyAreaRequest.name"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_point;
        break;
      }

      // repeated .PointMes point = 4;
      case 4: {
        if (tag == 34) {
         parse_point:
          DO_(input->IncrementRecursionDepth());
         parse_loop_point:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_point()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_loop_point;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(40)) goto parse_linestyle;
        break;
      }

      // optional int32 linestyle = 5;
      case 5: {
        if (tag == 40) {
         parse_linestyle:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &linestyle_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_fullstyle;
        break;
      }

      // optional int32 fullstyle = 6;
      case 6: {
        if (tag == 48) {
         parse_fullstyle:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &fullstyle_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(56)) goto parse_linewidth;
        break;
      }

      // optional int32 linewidth = 7;
      case 7: {
        if (tag == 56) {
         parse_linewidth:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &linewidth_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(66)) goto parse_dutyman;
        break;
      }

      // optional string dutyman = 8;
      case 8: {
        if (tag == 66) {
         parse_dutyman:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_dutyman()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->dutyman().data(), this->dutyman().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DutyAreaRequest.dutyman"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(74)) goto parse_drawman;
        break;
      }

      // optional string drawman = 9;
      case 9: {
        if (tag == 74) {
         parse_drawman:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_drawman()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->drawman().data(), this->drawman().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DutyAreaRequest.drawman"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(80)) goto parse_isshare;
        break;
      }

      // optional bool isshare = 10;
      case 10: {
        if (tag == 80) {
         parse_isshare:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &isshare_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(90)) goto parse_linecolor;
        break;
      }

      // optional string linecolor = 11;
      case 11: {
        if (tag == 90) {
         parse_linecolor:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_linecolor()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->linecolor().data(), this->linecolor().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DutyAreaRequest.linecolor"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(98)) goto parse_fullcolor;
        break;
      }

      // optional string fullcolor = 12;
      case 12: {
        if (tag == 98) {
         parse_fullcolor:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_fullcolor()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->fullcolor().data(), this->fullcolor().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DutyAreaRequest.fullcolor"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DutyAreaRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DutyAreaRequest)
  return false;
#undef DO_
}

void DutyAreaRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DutyAreaRequest)
  // optional int32 type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  // optional string ID = 2;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.ID");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->id(), output);
  }

  // optional string name = 3;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->name(), output);
  }

  // repeated .PointMes point = 4;
  for (unsigned int i = 0, n = this->point_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->point(i), output);
  }

  // optional int32 linestyle = 5;
  if (this->linestyle() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->linestyle(), output);
  }

  // optional int32 fullstyle = 6;
  if (this->fullstyle() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->fullstyle(), output);
  }

  // optional int32 linewidth = 7;
  if (this->linewidth() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(7, this->linewidth(), output);
  }

  // optional string dutyman = 8;
  if (this->dutyman().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dutyman().data(), this->dutyman().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.dutyman");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      8, this->dutyman(), output);
  }

  // optional string drawman = 9;
  if (this->drawman().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->drawman().data(), this->drawman().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.drawman");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      9, this->drawman(), output);
  }

  // optional bool isshare = 10;
  if (this->isshare() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(10, this->isshare(), output);
  }

  // optional string linecolor = 11;
  if (this->linecolor().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->linecolor().data(), this->linecolor().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.linecolor");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      11, this->linecolor(), output);
  }

  // optional string fullcolor = 12;
  if (this->fullcolor().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fullcolor().data(), this->fullcolor().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.fullcolor");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->fullcolor(), output);
  }

  // @@protoc_insertion_point(serialize_end:DutyAreaRequest)
}

::google::protobuf::uint8* DutyAreaRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DutyAreaRequest)
  // optional int32 type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  // optional string ID = 2;
  if (this->id().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->id().data(), this->id().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.ID");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->id(), target);
  }

  // optional string name = 3;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), this->name().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->name(), target);
  }

  // repeated .PointMes point = 4;
  for (unsigned int i = 0, n = this->point_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        4, this->point(i), false, target);
  }

  // optional int32 linestyle = 5;
  if (this->linestyle() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->linestyle(), target);
  }

  // optional int32 fullstyle = 6;
  if (this->fullstyle() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->fullstyle(), target);
  }

  // optional int32 linewidth = 7;
  if (this->linewidth() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(7, this->linewidth(), target);
  }

  // optional string dutyman = 8;
  if (this->dutyman().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->dutyman().data(), this->dutyman().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.dutyman");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        8, this->dutyman(), target);
  }

  // optional string drawman = 9;
  if (this->drawman().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->drawman().data(), this->drawman().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.drawman");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        9, this->drawman(), target);
  }

  // optional bool isshare = 10;
  if (this->isshare() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(10, this->isshare(), target);
  }

  // optional string linecolor = 11;
  if (this->linecolor().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->linecolor().data(), this->linecolor().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.linecolor");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        11, this->linecolor(), target);
  }

  // optional string fullcolor = 12;
  if (this->fullcolor().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->fullcolor().data(), this->fullcolor().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRequest.fullcolor");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->fullcolor(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DutyAreaRequest)
  return target;
}

size_t DutyAreaRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DutyAreaRequest)
  size_t total_size = 0;

  // optional int32 type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type());
  }

  // optional string ID = 2;
  if (this->id().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->id());
  }

  // optional string name = 3;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // optional int32 linestyle = 5;
  if (this->linestyle() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->linestyle());
  }

  // optional int32 fullstyle = 6;
  if (this->fullstyle() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->fullstyle());
  }

  // optional int32 linewidth = 7;
  if (this->linewidth() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->linewidth());
  }

  // optional string dutyman = 8;
  if (this->dutyman().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->dutyman());
  }

  // optional string drawman = 9;
  if (this->drawman().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->drawman());
  }

  // optional bool isshare = 10;
  if (this->isshare() != 0) {
    total_size += 1 + 1;
  }

  // optional string linecolor = 11;
  if (this->linecolor().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->linecolor());
  }

  // optional string fullcolor = 12;
  if (this->fullcolor().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->fullcolor());
  }

  // repeated .PointMes point = 4;
  {
    unsigned int count = this->point_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->point(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DutyAreaRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DutyAreaRequest)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const DutyAreaRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DutyAreaRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DutyAreaRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DutyAreaRequest)
    UnsafeMergeFrom(*source);
  }
}

void DutyAreaRequest::MergeFrom(const DutyAreaRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DutyAreaRequest)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void DutyAreaRequest::UnsafeMergeFrom(const DutyAreaRequest& from) {
  GOOGLE_DCHECK(&from != this);
  point_.MergeFrom(from.point_);
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.id().size() > 0) {

    id_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.id_);
  }
  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.linestyle() != 0) {
    set_linestyle(from.linestyle());
  }
  if (from.fullstyle() != 0) {
    set_fullstyle(from.fullstyle());
  }
  if (from.linewidth() != 0) {
    set_linewidth(from.linewidth());
  }
  if (from.dutyman().size() > 0) {

    dutyman_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.dutyman_);
  }
  if (from.drawman().size() > 0) {

    drawman_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.drawman_);
  }
  if (from.isshare() != 0) {
    set_isshare(from.isshare());
  }
  if (from.linecolor().size() > 0) {

    linecolor_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.linecolor_);
  }
  if (from.fullcolor().size() > 0) {

    fullcolor_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.fullcolor_);
  }
}

void DutyAreaRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DutyAreaRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DutyAreaRequest::CopyFrom(const DutyAreaRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DutyAreaRequest)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool DutyAreaRequest::IsInitialized() const {

  return true;
}

void DutyAreaRequest::Swap(DutyAreaRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DutyAreaRequest::InternalSwap(DutyAreaRequest* other) {
  std::swap(type_, other->type_);
  id_.Swap(&other->id_);
  name_.Swap(&other->name_);
  point_.UnsafeArenaSwap(&other->point_);
  std::swap(linestyle_, other->linestyle_);
  std::swap(fullstyle_, other->fullstyle_);
  std::swap(linewidth_, other->linewidth_);
  dutyman_.Swap(&other->dutyman_);
  drawman_.Swap(&other->drawman_);
  std::swap(isshare_, other->isshare_);
  linecolor_.Swap(&other->linecolor_);
  fullcolor_.Swap(&other->fullcolor_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DutyAreaRequest::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DutyAreaRequest_descriptor_;
  metadata.reflection = DutyAreaRequest_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DutyAreaRequest

// optional int32 type = 1;
void DutyAreaRequest::clear_type() {
  type_ = 0;
}
::google::protobuf::int32 DutyAreaRequest::type() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.type)
  return type_;
}
void DutyAreaRequest::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:DutyAreaRequest.type)
}

// optional string ID = 2;
void DutyAreaRequest::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DutyAreaRequest::id() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.ID)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_id(const ::std::string& value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DutyAreaRequest.ID)
}
void DutyAreaRequest::set_id(const char* value) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DutyAreaRequest.ID)
}
void DutyAreaRequest::set_id(const char* value, size_t size) {
  
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DutyAreaRequest.ID)
}
::std::string* DutyAreaRequest::mutable_id() {
  
  // @@protoc_insertion_point(field_mutable:DutyAreaRequest.ID)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DutyAreaRequest::release_id() {
  // @@protoc_insertion_point(field_release:DutyAreaRequest.ID)
  
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    
  } else {
    
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:DutyAreaRequest.ID)
}

// optional string name = 3;
void DutyAreaRequest::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DutyAreaRequest::name() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.name)
  return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DutyAreaRequest.name)
}
void DutyAreaRequest::set_name(const char* value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DutyAreaRequest.name)
}
void DutyAreaRequest::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DutyAreaRequest.name)
}
::std::string* DutyAreaRequest::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:DutyAreaRequest.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DutyAreaRequest::release_name() {
  // @@protoc_insertion_point(field_release:DutyAreaRequest.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:DutyAreaRequest.name)
}

// repeated .PointMes point = 4;
int DutyAreaRequest::point_size() const {
  return point_.size();
}
void DutyAreaRequest::clear_point() {
  point_.Clear();
}
const ::PointMes& DutyAreaRequest::point(int index) const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.point)
  return point_.Get(index);
}
::PointMes* DutyAreaRequest::mutable_point(int index) {
  // @@protoc_insertion_point(field_mutable:DutyAreaRequest.point)
  return point_.Mutable(index);
}
::PointMes* DutyAreaRequest::add_point() {
  // @@protoc_insertion_point(field_add:DutyAreaRequest.point)
  return point_.Add();
}
::google::protobuf::RepeatedPtrField< ::PointMes >*
DutyAreaRequest::mutable_point() {
  // @@protoc_insertion_point(field_mutable_list:DutyAreaRequest.point)
  return &point_;
}
const ::google::protobuf::RepeatedPtrField< ::PointMes >&
DutyAreaRequest::point() const {
  // @@protoc_insertion_point(field_list:DutyAreaRequest.point)
  return point_;
}

// optional int32 linestyle = 5;
void DutyAreaRequest::clear_linestyle() {
  linestyle_ = 0;
}
::google::protobuf::int32 DutyAreaRequest::linestyle() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.linestyle)
  return linestyle_;
}
void DutyAreaRequest::set_linestyle(::google::protobuf::int32 value) {
  
  linestyle_ = value;
  // @@protoc_insertion_point(field_set:DutyAreaRequest.linestyle)
}

// optional int32 fullstyle = 6;
void DutyAreaRequest::clear_fullstyle() {
  fullstyle_ = 0;
}
::google::protobuf::int32 DutyAreaRequest::fullstyle() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.fullstyle)
  return fullstyle_;
}
void DutyAreaRequest::set_fullstyle(::google::protobuf::int32 value) {
  
  fullstyle_ = value;
  // @@protoc_insertion_point(field_set:DutyAreaRequest.fullstyle)
}

// optional int32 linewidth = 7;
void DutyAreaRequest::clear_linewidth() {
  linewidth_ = 0;
}
::google::protobuf::int32 DutyAreaRequest::linewidth() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.linewidth)
  return linewidth_;
}
void DutyAreaRequest::set_linewidth(::google::protobuf::int32 value) {
  
  linewidth_ = value;
  // @@protoc_insertion_point(field_set:DutyAreaRequest.linewidth)
}

// optional string dutyman = 8;
void DutyAreaRequest::clear_dutyman() {
  dutyman_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DutyAreaRequest::dutyman() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.dutyman)
  return dutyman_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_dutyman(const ::std::string& value) {
  
  dutyman_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DutyAreaRequest.dutyman)
}
void DutyAreaRequest::set_dutyman(const char* value) {
  
  dutyman_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DutyAreaRequest.dutyman)
}
void DutyAreaRequest::set_dutyman(const char* value, size_t size) {
  
  dutyman_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DutyAreaRequest.dutyman)
}
::std::string* DutyAreaRequest::mutable_dutyman() {
  
  // @@protoc_insertion_point(field_mutable:DutyAreaRequest.dutyman)
  return dutyman_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DutyAreaRequest::release_dutyman() {
  // @@protoc_insertion_point(field_release:DutyAreaRequest.dutyman)
  
  return dutyman_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_allocated_dutyman(::std::string* dutyman) {
  if (dutyman != NULL) {
    
  } else {
    
  }
  dutyman_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), dutyman);
  // @@protoc_insertion_point(field_set_allocated:DutyAreaRequest.dutyman)
}

// optional string drawman = 9;
void DutyAreaRequest::clear_drawman() {
  drawman_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DutyAreaRequest::drawman() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.drawman)
  return drawman_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_drawman(const ::std::string& value) {
  
  drawman_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DutyAreaRequest.drawman)
}
void DutyAreaRequest::set_drawman(const char* value) {
  
  drawman_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DutyAreaRequest.drawman)
}
void DutyAreaRequest::set_drawman(const char* value, size_t size) {
  
  drawman_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DutyAreaRequest.drawman)
}
::std::string* DutyAreaRequest::mutable_drawman() {
  
  // @@protoc_insertion_point(field_mutable:DutyAreaRequest.drawman)
  return drawman_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DutyAreaRequest::release_drawman() {
  // @@protoc_insertion_point(field_release:DutyAreaRequest.drawman)
  
  return drawman_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_allocated_drawman(::std::string* drawman) {
  if (drawman != NULL) {
    
  } else {
    
  }
  drawman_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), drawman);
  // @@protoc_insertion_point(field_set_allocated:DutyAreaRequest.drawman)
}

// optional bool isshare = 10;
void DutyAreaRequest::clear_isshare() {
  isshare_ = false;
}
bool DutyAreaRequest::isshare() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.isshare)
  return isshare_;
}
void DutyAreaRequest::set_isshare(bool value) {
  
  isshare_ = value;
  // @@protoc_insertion_point(field_set:DutyAreaRequest.isshare)
}

// optional string linecolor = 11;
void DutyAreaRequest::clear_linecolor() {
  linecolor_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DutyAreaRequest::linecolor() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.linecolor)
  return linecolor_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_linecolor(const ::std::string& value) {
  
  linecolor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DutyAreaRequest.linecolor)
}
void DutyAreaRequest::set_linecolor(const char* value) {
  
  linecolor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DutyAreaRequest.linecolor)
}
void DutyAreaRequest::set_linecolor(const char* value, size_t size) {
  
  linecolor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DutyAreaRequest.linecolor)
}
::std::string* DutyAreaRequest::mutable_linecolor() {
  
  // @@protoc_insertion_point(field_mutable:DutyAreaRequest.linecolor)
  return linecolor_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DutyAreaRequest::release_linecolor() {
  // @@protoc_insertion_point(field_release:DutyAreaRequest.linecolor)
  
  return linecolor_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_allocated_linecolor(::std::string* linecolor) {
  if (linecolor != NULL) {
    
  } else {
    
  }
  linecolor_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), linecolor);
  // @@protoc_insertion_point(field_set_allocated:DutyAreaRequest.linecolor)
}

// optional string fullcolor = 12;
void DutyAreaRequest::clear_fullcolor() {
  fullcolor_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DutyAreaRequest::fullcolor() const {
  // @@protoc_insertion_point(field_get:DutyAreaRequest.fullcolor)
  return fullcolor_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_fullcolor(const ::std::string& value) {
  
  fullcolor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DutyAreaRequest.fullcolor)
}
void DutyAreaRequest::set_fullcolor(const char* value) {
  
  fullcolor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DutyAreaRequest.fullcolor)
}
void DutyAreaRequest::set_fullcolor(const char* value, size_t size) {
  
  fullcolor_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DutyAreaRequest.fullcolor)
}
::std::string* DutyAreaRequest::mutable_fullcolor() {
  
  // @@protoc_insertion_point(field_mutable:DutyAreaRequest.fullcolor)
  return fullcolor_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DutyAreaRequest::release_fullcolor() {
  // @@protoc_insertion_point(field_release:DutyAreaRequest.fullcolor)
  
  return fullcolor_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRequest::set_allocated_fullcolor(::std::string* fullcolor) {
  if (fullcolor != NULL) {
    
  } else {
    
  }
  fullcolor_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), fullcolor);
  // @@protoc_insertion_point(field_set_allocated:DutyAreaRequest.fullcolor)
}

inline const DutyAreaRequest* DutyAreaRequest::internal_default_instance() {
  return &DutyAreaRequest_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DutyAreaRepsone::kTypeFieldNumber;
const int DutyAreaRepsone::kResultFieldNumber;
const int DutyAreaRepsone::kDutyareasFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DutyAreaRepsone::DutyAreaRepsone()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_dutyarea_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:DutyAreaRepsone)
}

void DutyAreaRepsone::InitAsDefaultInstance() {
}

DutyAreaRepsone::DutyAreaRepsone(const DutyAreaRepsone& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:DutyAreaRepsone)
}

void DutyAreaRepsone::SharedCtor() {
  result_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_ = 0;
  _cached_size_ = 0;
}

DutyAreaRepsone::~DutyAreaRepsone() {
  // @@protoc_insertion_point(destructor:DutyAreaRepsone)
  SharedDtor();
}

void DutyAreaRepsone::SharedDtor() {
  result_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void DutyAreaRepsone::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DutyAreaRepsone::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return DutyAreaRepsone_descriptor_;
}

const DutyAreaRepsone& DutyAreaRepsone::default_instance() {
  protobuf_InitDefaults_dutyarea_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<DutyAreaRepsone> DutyAreaRepsone_default_instance_;

DutyAreaRepsone* DutyAreaRepsone::New(::google::protobuf::Arena* arena) const {
  DutyAreaRepsone* n = new DutyAreaRepsone;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DutyAreaRepsone::Clear() {
// @@protoc_insertion_point(message_clear_start:DutyAreaRepsone)
  type_ = 0;
  result_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  dutyareas_.Clear();
}

bool DutyAreaRepsone::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:DutyAreaRepsone)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 type = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_result;
        break;
      }

      // optional string result = 2;
      case 2: {
        if (tag == 18) {
         parse_result:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_result()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->result().data(), this->result().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "DutyAreaRepsone.result"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_dutyareas;
        break;
      }

      // repeated .DutyAreaRequest dutyareas = 3;
      case 3: {
        if (tag == 26) {
         parse_dutyareas:
          DO_(input->IncrementRecursionDepth());
         parse_loop_dutyareas:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_dutyareas()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_loop_dutyareas;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:DutyAreaRepsone)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:DutyAreaRepsone)
  return false;
#undef DO_
}

void DutyAreaRepsone::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:DutyAreaRepsone)
  // optional int32 type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->type(), output);
  }

  // optional string result = 2;
  if (this->result().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->result().data(), this->result().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRepsone.result");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->result(), output);
  }

  // repeated .DutyAreaRequest dutyareas = 3;
  for (unsigned int i = 0, n = this->dutyareas_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, this->dutyareas(i), output);
  }

  // @@protoc_insertion_point(serialize_end:DutyAreaRepsone)
}

::google::protobuf::uint8* DutyAreaRepsone::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:DutyAreaRepsone)
  // optional int32 type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->type(), target);
  }

  // optional string result = 2;
  if (this->result().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->result().data(), this->result().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "DutyAreaRepsone.result");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->result(), target);
  }

  // repeated .DutyAreaRequest dutyareas = 3;
  for (unsigned int i = 0, n = this->dutyareas_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, this->dutyareas(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:DutyAreaRepsone)
  return target;
}

size_t DutyAreaRepsone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:DutyAreaRepsone)
  size_t total_size = 0;

  // optional int32 type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type());
  }

  // optional string result = 2;
  if (this->result().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->result());
  }

  // repeated .DutyAreaRequest dutyareas = 3;
  {
    unsigned int count = this->dutyareas_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->dutyareas(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DutyAreaRepsone::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:DutyAreaRepsone)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const DutyAreaRepsone* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DutyAreaRepsone>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:DutyAreaRepsone)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:DutyAreaRepsone)
    UnsafeMergeFrom(*source);
  }
}

void DutyAreaRepsone::MergeFrom(const DutyAreaRepsone& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:DutyAreaRepsone)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void DutyAreaRepsone::UnsafeMergeFrom(const DutyAreaRepsone& from) {
  GOOGLE_DCHECK(&from != this);
  dutyareas_.MergeFrom(from.dutyareas_);
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.result().size() > 0) {

    result_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.result_);
  }
}

void DutyAreaRepsone::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:DutyAreaRepsone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DutyAreaRepsone::CopyFrom(const DutyAreaRepsone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:DutyAreaRepsone)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool DutyAreaRepsone::IsInitialized() const {

  return true;
}

void DutyAreaRepsone::Swap(DutyAreaRepsone* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DutyAreaRepsone::InternalSwap(DutyAreaRepsone* other) {
  std::swap(type_, other->type_);
  result_.Swap(&other->result_);
  dutyareas_.UnsafeArenaSwap(&other->dutyareas_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DutyAreaRepsone::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = DutyAreaRepsone_descriptor_;
  metadata.reflection = DutyAreaRepsone_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// DutyAreaRepsone

// optional int32 type = 1;
void DutyAreaRepsone::clear_type() {
  type_ = 0;
}
::google::protobuf::int32 DutyAreaRepsone::type() const {
  // @@protoc_insertion_point(field_get:DutyAreaRepsone.type)
  return type_;
}
void DutyAreaRepsone::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:DutyAreaRepsone.type)
}

// optional string result = 2;
void DutyAreaRepsone::clear_result() {
  result_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& DutyAreaRepsone::result() const {
  // @@protoc_insertion_point(field_get:DutyAreaRepsone.result)
  return result_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRepsone::set_result(const ::std::string& value) {
  
  result_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DutyAreaRepsone.result)
}
void DutyAreaRepsone::set_result(const char* value) {
  
  result_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DutyAreaRepsone.result)
}
void DutyAreaRepsone::set_result(const char* value, size_t size) {
  
  result_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DutyAreaRepsone.result)
}
::std::string* DutyAreaRepsone::mutable_result() {
  
  // @@protoc_insertion_point(field_mutable:DutyAreaRepsone.result)
  return result_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* DutyAreaRepsone::release_result() {
  // @@protoc_insertion_point(field_release:DutyAreaRepsone.result)
  
  return result_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void DutyAreaRepsone::set_allocated_result(::std::string* result) {
  if (result != NULL) {
    
  } else {
    
  }
  result_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), result);
  // @@protoc_insertion_point(field_set_allocated:DutyAreaRepsone.result)
}

// repeated .DutyAreaRequest dutyareas = 3;
int DutyAreaRepsone::dutyareas_size() const {
  return dutyareas_.size();
}
void DutyAreaRepsone::clear_dutyareas() {
  dutyareas_.Clear();
}
const ::DutyAreaRequest& DutyAreaRepsone::dutyareas(int index) const {
  // @@protoc_insertion_point(field_get:DutyAreaRepsone.dutyareas)
  return dutyareas_.Get(index);
}
::DutyAreaRequest* DutyAreaRepsone::mutable_dutyareas(int index) {
  // @@protoc_insertion_point(field_mutable:DutyAreaRepsone.dutyareas)
  return dutyareas_.Mutable(index);
}
::DutyAreaRequest* DutyAreaRepsone::add_dutyareas() {
  // @@protoc_insertion_point(field_add:DutyAreaRepsone.dutyareas)
  return dutyareas_.Add();
}
::google::protobuf::RepeatedPtrField< ::DutyAreaRequest >*
DutyAreaRepsone::mutable_dutyareas() {
  // @@protoc_insertion_point(field_mutable_list:DutyAreaRepsone.dutyareas)
  return &dutyareas_;
}
const ::google::protobuf::RepeatedPtrField< ::DutyAreaRequest >&
DutyAreaRepsone::dutyareas() const {
  // @@protoc_insertion_point(field_list:DutyAreaRepsone.dutyareas)
  return dutyareas_;
}

inline const DutyAreaRepsone* DutyAreaRepsone::internal_default_instance() {
  return &DutyAreaRepsone_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
