// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hgHeartBeat.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "hgHeartBeat.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* hgHeartBeatPack_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  hgHeartBeatPack_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_hgHeartBeat_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_hgHeartBeat_2eproto() {
  protobuf_AddDesc_hgHeartBeat_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "hgHeartBeat.proto");
  GOOGLE_CHECK(file != NULL);
  hgHeartBeatPack_descriptor_ = file->message_type(0);
  static const int hgHeartBeatPack_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hgHeartBeatPack, heart_),
  };
  hgHeartBeatPack_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      hgHeartBeatPack_descriptor_,
      hgHeartBeatPack::internal_default_instance(),
      hgHeartBeatPack_offsets_,
      -1,
      -1,
      -1,
      sizeof(hgHeartBeatPack),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hgHeartBeatPack, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_hgHeartBeat_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      hgHeartBeatPack_descriptor_, hgHeartBeatPack::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_hgHeartBeat_2eproto() {
  hgHeartBeatPack_default_instance_.Shutdown();
  delete hgHeartBeatPack_reflection_;
}

void protobuf_InitDefaults_hgHeartBeat_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  hgHeartBeatPack_default_instance_.DefaultConstruct();
  hgHeartBeatPack_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_hgHeartBeat_2eproto_once_);
void protobuf_InitDefaults_hgHeartBeat_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_hgHeartBeat_2eproto_once_,
                 &protobuf_InitDefaults_hgHeartBeat_2eproto_impl);
}
void protobuf_AddDesc_hgHeartBeat_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_hgHeartBeat_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021hgHeartBeat.proto\" \n\017hgHeartBeatPack\022\r"
    "\n\005heart\030\001 \001(\005b\006proto3", 61);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "hgHeartBeat.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_hgHeartBeat_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_hgHeartBeat_2eproto_once_);
void protobuf_AddDesc_hgHeartBeat_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_hgHeartBeat_2eproto_once_,
                 &protobuf_AddDesc_hgHeartBeat_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_hgHeartBeat_2eproto {
  StaticDescriptorInitializer_hgHeartBeat_2eproto() {
    protobuf_AddDesc_hgHeartBeat_2eproto();
  }
} static_descriptor_initializer_hgHeartBeat_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int hgHeartBeatPack::kHeartFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

hgHeartBeatPack::hgHeartBeatPack()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_hgHeartBeat_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:hgHeartBeatPack)
}

void hgHeartBeatPack::InitAsDefaultInstance() {
}

hgHeartBeatPack::hgHeartBeatPack(const hgHeartBeatPack& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:hgHeartBeatPack)
}

void hgHeartBeatPack::SharedCtor() {
  heart_ = 0;
  _cached_size_ = 0;
}

hgHeartBeatPack::~hgHeartBeatPack() {
  // @@protoc_insertion_point(destructor:hgHeartBeatPack)
  SharedDtor();
}

void hgHeartBeatPack::SharedDtor() {
}

void hgHeartBeatPack::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* hgHeartBeatPack::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return hgHeartBeatPack_descriptor_;
}

const hgHeartBeatPack& hgHeartBeatPack::default_instance() {
  protobuf_InitDefaults_hgHeartBeat_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<hgHeartBeatPack> hgHeartBeatPack_default_instance_;

hgHeartBeatPack* hgHeartBeatPack::New(::google::protobuf::Arena* arena) const {
  hgHeartBeatPack* n = new hgHeartBeatPack;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void hgHeartBeatPack::Clear() {
// @@protoc_insertion_point(message_clear_start:hgHeartBeatPack)
  heart_ = 0;
}

bool hgHeartBeatPack::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hgHeartBeatPack)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 heart = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &heart_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hgHeartBeatPack)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hgHeartBeatPack)
  return false;
#undef DO_
}

void hgHeartBeatPack::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hgHeartBeatPack)
  // optional int32 heart = 1;
  if (this->heart() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->heart(), output);
  }

  // @@protoc_insertion_point(serialize_end:hgHeartBeatPack)
}

::google::protobuf::uint8* hgHeartBeatPack::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:hgHeartBeatPack)
  // optional int32 heart = 1;
  if (this->heart() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->heart(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:hgHeartBeatPack)
  return target;
}

size_t hgHeartBeatPack::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hgHeartBeatPack)
  size_t total_size = 0;

  // optional int32 heart = 1;
  if (this->heart() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->heart());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void hgHeartBeatPack::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hgHeartBeatPack)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const hgHeartBeatPack* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const hgHeartBeatPack>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hgHeartBeatPack)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hgHeartBeatPack)
    UnsafeMergeFrom(*source);
  }
}

void hgHeartBeatPack::MergeFrom(const hgHeartBeatPack& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hgHeartBeatPack)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void hgHeartBeatPack::UnsafeMergeFrom(const hgHeartBeatPack& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.heart() != 0) {
    set_heart(from.heart());
  }
}

void hgHeartBeatPack::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hgHeartBeatPack)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void hgHeartBeatPack::CopyFrom(const hgHeartBeatPack& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hgHeartBeatPack)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool hgHeartBeatPack::IsInitialized() const {

  return true;
}

void hgHeartBeatPack::Swap(hgHeartBeatPack* other) {
  if (other == this) return;
  InternalSwap(other);
}
void hgHeartBeatPack::InternalSwap(hgHeartBeatPack* other) {
  std::swap(heart_, other->heart_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata hgHeartBeatPack::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = hgHeartBeatPack_descriptor_;
  metadata.reflection = hgHeartBeatPack_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// hgHeartBeatPack

// optional int32 heart = 1;
void hgHeartBeatPack::clear_heart() {
  heart_ = 0;
}
::google::protobuf::int32 hgHeartBeatPack::heart() const {
  // @@protoc_insertion_point(field_get:hgHeartBeatPack.heart)
  return heart_;
}
void hgHeartBeatPack::set_heart(::google::protobuf::int32 value) {
  
  heart_ = value;
  // @@protoc_insertion_point(field_set:hgHeartBeatPack.heart)
}

inline const hgHeartBeatPack* hgHeartBeatPack::internal_default_instance() {
  return &hgHeartBeatPack_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
