// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hgShipHdg.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "hgShipHdg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* hgShipHdg_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  hgShipHdg_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_hgShipHdg_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_hgShipHdg_2eproto() {
  protobuf_AddDesc_hgShipHdg_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "hgShipHdg.proto");
  GOOGLE_CHECK(file != NULL);
  hgShipHdg_descriptor_ = file->message_type(0);
  static const int hgShipHdg_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hgShipHdg, mmsi_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hgShipHdg, type_),
  };
  hgShipHdg_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      hgShipHdg_descriptor_,
      hgShipHdg::internal_default_instance(),
      hgShipHdg_offsets_,
      -1,
      -1,
      -1,
      sizeof(hgShipHdg),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(hgShipHdg, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_hgShipHdg_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      hgShipHdg_descriptor_, hgShipHdg::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_hgShipHdg_2eproto() {
  hgShipHdg_default_instance_.Shutdown();
  delete hgShipHdg_reflection_;
}

void protobuf_InitDefaults_hgShipHdg_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  hgShipHdg_default_instance_.DefaultConstruct();
  hgShipHdg_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_hgShipHdg_2eproto_once_);
void protobuf_InitDefaults_hgShipHdg_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_hgShipHdg_2eproto_once_,
                 &protobuf_InitDefaults_hgShipHdg_2eproto_impl);
}
void protobuf_AddDesc_hgShipHdg_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_hgShipHdg_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\017hgShipHdg.proto\"\'\n\thgShipHdg\022\014\n\004MMSI\030\001"
    " \001(\t\022\014\n\004type\030\002 \001(\005b\006proto3", 66);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "hgShipHdg.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_hgShipHdg_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_hgShipHdg_2eproto_once_);
void protobuf_AddDesc_hgShipHdg_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_hgShipHdg_2eproto_once_,
                 &protobuf_AddDesc_hgShipHdg_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_hgShipHdg_2eproto {
  StaticDescriptorInitializer_hgShipHdg_2eproto() {
    protobuf_AddDesc_hgShipHdg_2eproto();
  }
} static_descriptor_initializer_hgShipHdg_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int hgShipHdg::kMMSIFieldNumber;
const int hgShipHdg::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

hgShipHdg::hgShipHdg()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_hgShipHdg_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:hgShipHdg)
}

void hgShipHdg::InitAsDefaultInstance() {
}

hgShipHdg::hgShipHdg(const hgShipHdg& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:hgShipHdg)
}

void hgShipHdg::SharedCtor() {
  mmsi_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_ = 0;
  _cached_size_ = 0;
}

hgShipHdg::~hgShipHdg() {
  // @@protoc_insertion_point(destructor:hgShipHdg)
  SharedDtor();
}

void hgShipHdg::SharedDtor() {
  mmsi_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void hgShipHdg::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* hgShipHdg::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return hgShipHdg_descriptor_;
}

const hgShipHdg& hgShipHdg::default_instance() {
  protobuf_InitDefaults_hgShipHdg_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<hgShipHdg> hgShipHdg_default_instance_;

hgShipHdg* hgShipHdg::New(::google::protobuf::Arena* arena) const {
  hgShipHdg* n = new hgShipHdg;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void hgShipHdg::Clear() {
// @@protoc_insertion_point(message_clear_start:hgShipHdg)
  mmsi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  type_ = 0;
}

bool hgShipHdg::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:hgShipHdg)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string MMSI = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_mmsi()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->mmsi().data(), this->mmsi().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "hgShipHdg.MMSI"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_type;
        break;
      }

      // optional int32 type = 2;
      case 2: {
        if (tag == 16) {
         parse_type:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &type_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:hgShipHdg)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:hgShipHdg)
  return false;
#undef DO_
}

void hgShipHdg::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:hgShipHdg)
  // optional string MMSI = 1;
  if (this->mmsi().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mmsi().data(), this->mmsi().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "hgShipHdg.MMSI");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->mmsi(), output);
  }

  // optional int32 type = 2;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->type(), output);
  }

  // @@protoc_insertion_point(serialize_end:hgShipHdg)
}

::google::protobuf::uint8* hgShipHdg::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:hgShipHdg)
  // optional string MMSI = 1;
  if (this->mmsi().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->mmsi().data(), this->mmsi().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "hgShipHdg.MMSI");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->mmsi(), target);
  }

  // optional int32 type = 2;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->type(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:hgShipHdg)
  return target;
}

size_t hgShipHdg::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:hgShipHdg)
  size_t total_size = 0;

  // optional string MMSI = 1;
  if (this->mmsi().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->mmsi());
  }

  // optional int32 type = 2;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void hgShipHdg::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:hgShipHdg)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const hgShipHdg* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const hgShipHdg>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:hgShipHdg)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:hgShipHdg)
    UnsafeMergeFrom(*source);
  }
}

void hgShipHdg::MergeFrom(const hgShipHdg& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:hgShipHdg)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void hgShipHdg::UnsafeMergeFrom(const hgShipHdg& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.mmsi().size() > 0) {

    mmsi_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.mmsi_);
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void hgShipHdg::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:hgShipHdg)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void hgShipHdg::CopyFrom(const hgShipHdg& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:hgShipHdg)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool hgShipHdg::IsInitialized() const {

  return true;
}

void hgShipHdg::Swap(hgShipHdg* other) {
  if (other == this) return;
  InternalSwap(other);
}
void hgShipHdg::InternalSwap(hgShipHdg* other) {
  mmsi_.Swap(&other->mmsi_);
  std::swap(type_, other->type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata hgShipHdg::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = hgShipHdg_descriptor_;
  metadata.reflection = hgShipHdg_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// hgShipHdg

// optional string MMSI = 1;
void hgShipHdg::clear_mmsi() {
  mmsi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& hgShipHdg::mmsi() const {
  // @@protoc_insertion_point(field_get:hgShipHdg.MMSI)
  return mmsi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void hgShipHdg::set_mmsi(const ::std::string& value) {
  
  mmsi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hgShipHdg.MMSI)
}
void hgShipHdg::set_mmsi(const char* value) {
  
  mmsi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hgShipHdg.MMSI)
}
void hgShipHdg::set_mmsi(const char* value, size_t size) {
  
  mmsi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hgShipHdg.MMSI)
}
::std::string* hgShipHdg::mutable_mmsi() {
  
  // @@protoc_insertion_point(field_mutable:hgShipHdg.MMSI)
  return mmsi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* hgShipHdg::release_mmsi() {
  // @@protoc_insertion_point(field_release:hgShipHdg.MMSI)
  
  return mmsi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void hgShipHdg::set_allocated_mmsi(::std::string* mmsi) {
  if (mmsi != NULL) {
    
  } else {
    
  }
  mmsi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mmsi);
  // @@protoc_insertion_point(field_set_allocated:hgShipHdg.MMSI)
}

// optional int32 type = 2;
void hgShipHdg::clear_type() {
  type_ = 0;
}
::google::protobuf::int32 hgShipHdg::type() const {
  // @@protoc_insertion_point(field_get:hgShipHdg.type)
  return type_;
}
void hgShipHdg::set_type(::google::protobuf::int32 value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:hgShipHdg.type)
}

inline const hgShipHdg* hgShipHdg::internal_default_instance() {
  return &hgShipHdg_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
