// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hgTurnCircle.proto

#ifndef PROTOBUF_hgTurnCircle_2eproto__INCLUDED
#define PROTOBUF_hgTurnCircle_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_hgTurnCircle_2eproto();
void protobuf_InitDefaults_hgTurnCircle_2eproto();
void protobuf_AssignDesc_hgTurnCircle_2eproto();
void protobuf_ShutdownFile_hgTurnCircle_2eproto();

class hgTurnCircle;
class hgTurnCircleRepsone;

// ===================================================================

class hgTurnCircle : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hgTurnCircle) */ {
 public:
  hgTurnCircle();
  virtual ~hgTurnCircle();

  hgTurnCircle(const hgTurnCircle& from);

  inline hgTurnCircle& operator=(const hgTurnCircle& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const hgTurnCircle& default_instance();

  static const hgTurnCircle* internal_default_instance();

  void Swap(hgTurnCircle* other);

  // implements Message ----------------------------------------------

  inline hgTurnCircle* New() const { return New(NULL); }

  hgTurnCircle* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const hgTurnCircle& from);
  void MergeFrom(const hgTurnCircle& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(hgTurnCircle* other);
  void UnsafeMergeFrom(const hgTurnCircle& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string MMSI = 1;
  void clear_mmsi();
  static const int kMMSIFieldNumber = 1;
  const ::std::string& mmsi() const;
  void set_mmsi(const ::std::string& value);
  void set_mmsi(const char* value);
  void set_mmsi(const char* value, size_t size);
  ::std::string* mutable_mmsi();
  ::std::string* release_mmsi();
  void set_allocated_mmsi(::std::string* mmsi);

  // optional bool TurnCircle = 2;
  void clear_turncircle();
  static const int kTurnCircleFieldNumber = 2;
  bool turncircle() const;
  void set_turncircle(bool value);

  // optional double Radius = 3;
  void clear_radius();
  static const int kRadiusFieldNumber = 3;
  double radius() const;
  void set_radius(double value);

  // optional double Lat = 4;
  void clear_lat();
  static const int kLatFieldNumber = 4;
  double lat() const;
  void set_lat(double value);

  // optional double Lon = 5;
  void clear_lon();
  static const int kLonFieldNumber = 5;
  double lon() const;
  void set_lon(double value);

  // @@protoc_insertion_point(class_scope:hgTurnCircle)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr mmsi_;
  double radius_;
  double lat_;
  double lon_;
  bool turncircle_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_hgTurnCircle_2eproto_impl();
  friend void  protobuf_AddDesc_hgTurnCircle_2eproto_impl();
  friend void protobuf_AssignDesc_hgTurnCircle_2eproto();
  friend void protobuf_ShutdownFile_hgTurnCircle_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<hgTurnCircle> hgTurnCircle_default_instance_;

// -------------------------------------------------------------------

class hgTurnCircleRepsone : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:hgTurnCircleRepsone) */ {
 public:
  hgTurnCircleRepsone();
  virtual ~hgTurnCircleRepsone();

  hgTurnCircleRepsone(const hgTurnCircleRepsone& from);

  inline hgTurnCircleRepsone& operator=(const hgTurnCircleRepsone& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const hgTurnCircleRepsone& default_instance();

  static const hgTurnCircleRepsone* internal_default_instance();

  void Swap(hgTurnCircleRepsone* other);

  // implements Message ----------------------------------------------

  inline hgTurnCircleRepsone* New() const { return New(NULL); }

  hgTurnCircleRepsone* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const hgTurnCircleRepsone& from);
  void MergeFrom(const hgTurnCircleRepsone& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(hgTurnCircleRepsone* other);
  void UnsafeMergeFrom(const hgTurnCircleRepsone& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hgTurnCircleRepsone)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_hgTurnCircle_2eproto_impl();
  friend void  protobuf_AddDesc_hgTurnCircle_2eproto_impl();
  friend void protobuf_AssignDesc_hgTurnCircle_2eproto();
  friend void protobuf_ShutdownFile_hgTurnCircle_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<hgTurnCircleRepsone> hgTurnCircleRepsone_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// hgTurnCircle

// optional string MMSI = 1;
inline void hgTurnCircle::clear_mmsi() {
  mmsi_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& hgTurnCircle::mmsi() const {
  // @@protoc_insertion_point(field_get:hgTurnCircle.MMSI)
  return mmsi_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void hgTurnCircle::set_mmsi(const ::std::string& value) {
  
  mmsi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:hgTurnCircle.MMSI)
}
inline void hgTurnCircle::set_mmsi(const char* value) {
  
  mmsi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:hgTurnCircle.MMSI)
}
inline void hgTurnCircle::set_mmsi(const char* value, size_t size) {
  
  mmsi_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:hgTurnCircle.MMSI)
}
inline ::std::string* hgTurnCircle::mutable_mmsi() {
  
  // @@protoc_insertion_point(field_mutable:hgTurnCircle.MMSI)
  return mmsi_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* hgTurnCircle::release_mmsi() {
  // @@protoc_insertion_point(field_release:hgTurnCircle.MMSI)
  
  return mmsi_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void hgTurnCircle::set_allocated_mmsi(::std::string* mmsi) {
  if (mmsi != NULL) {
    
  } else {
    
  }
  mmsi_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), mmsi);
  // @@protoc_insertion_point(field_set_allocated:hgTurnCircle.MMSI)
}

// optional bool TurnCircle = 2;
inline void hgTurnCircle::clear_turncircle() {
  turncircle_ = false;
}
inline bool hgTurnCircle::turncircle() const {
  // @@protoc_insertion_point(field_get:hgTurnCircle.TurnCircle)
  return turncircle_;
}
inline void hgTurnCircle::set_turncircle(bool value) {
  
  turncircle_ = value;
  // @@protoc_insertion_point(field_set:hgTurnCircle.TurnCircle)
}

// optional double Radius = 3;
inline void hgTurnCircle::clear_radius() {
  radius_ = 0;
}
inline double hgTurnCircle::radius() const {
  // @@protoc_insertion_point(field_get:hgTurnCircle.Radius)
  return radius_;
}
inline void hgTurnCircle::set_radius(double value) {
  
  radius_ = value;
  // @@protoc_insertion_point(field_set:hgTurnCircle.Radius)
}

// optional double Lat = 4;
inline void hgTurnCircle::clear_lat() {
  lat_ = 0;
}
inline double hgTurnCircle::lat() const {
  // @@protoc_insertion_point(field_get:hgTurnCircle.Lat)
  return lat_;
}
inline void hgTurnCircle::set_lat(double value) {
  
  lat_ = value;
  // @@protoc_insertion_point(field_set:hgTurnCircle.Lat)
}

// optional double Lon = 5;
inline void hgTurnCircle::clear_lon() {
  lon_ = 0;
}
inline double hgTurnCircle::lon() const {
  // @@protoc_insertion_point(field_get:hgTurnCircle.Lon)
  return lon_;
}
inline void hgTurnCircle::set_lon(double value) {
  
  lon_ = value;
  // @@protoc_insertion_point(field_set:hgTurnCircle.Lon)
}

inline const hgTurnCircle* hgTurnCircle::internal_default_instance() {
  return &hgTurnCircle_default_instance_.get();
}
// -------------------------------------------------------------------

// hgTurnCircleRepsone

inline const hgTurnCircleRepsone* hgTurnCircleRepsone::internal_default_instance() {
  return &hgTurnCircleRepsone_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_hgTurnCircle_2eproto__INCLUDED
